### ISSUE TITLE
Lack of libs

### ISSUE THREAD

**Issue by lethanhtrung2020** [arrowjs/CMS#17]
## After cloning cms from git, up & running -> console shows some 404 messages as below

GET /frontend/acme/assets/libs/bxslider/jquery.bxslider.js 404 6.069 ms - 9
GET /images/slider/img2.png 404 9.914 ms - 9
GET /frontend/acme/assets/libs/owlcarousel/owl.carousel.js 404 11.142 ms - 9
GET /frontend/acme/assets/libs/bxslider/jquery.bxslider.js 404 9.892 ms - 9
## GET /frontend/acme/assets/libs/owlcarousel/owl.carousel.js 404 5.339 ms - 9

site seems to be ok but don't know any impact.

**Comment by thangtyt** [comment]
This issue is fixed in new version.
