### ISSUE TITLE
Don't know how to attach Menu to site

### ISSUE THREAD

**Issue by lethanhtrung2020** [arrowjs/CMS#18]
There is a function to manage menus there. I created a menu, named Main, and a menu item, linked to a page.
But I don't know to to get the menu appeared on my site.
Note that I am using Corlate theme

**Comment by thangtyt** [comment]
Hi,
You must using feature 'widgets Manager" to add menus (remember to click 'save' button after drag menu to widget) then you reload frontend page, you can see menu.
