### ISSUE TITLE
Wrong display backend menu when user update roles.

### ISSUE THREAD

**Issue by thangtyt** [arrowjs/CMS#23]
backend menu without roles still display menu items. Have problems with check permissions in backend menu.

**Comment by TechMaster** [comment]
Sửa đi !

**Comment by thangtyt** [comment]
Founded problem ! 

Must using ArrowCMS with redis server. Default fakeredis didn't store value of widgets features.

1. install redis server : http://redis.io/
2. edit config/redis.js file to change value : 
_redis: {
        host: 'localhost',
        port: '6379',
        type: '**fakeredis**' // change to redis
    },_

**Comment by thangtyt** [comment]
fixed
