### ISSUE TITLE
Menu Menu Menu :(

### ISSUE THREAD

**Issue by lethanhtrung2020** [arrowjs/CMS#28]
clone lastest version, fresh DB. But still get stuck with menu :(. View image below for detail
It seems that the issue happens to the first menu item only

![s1](https://cloud.githubusercontent.com/assets/14961790/13547599/d234fcb2-e30b-11e5-8074-306d9921bf12.png)

![s2](https://cloud.githubusercontent.com/assets/14961790/13547594/cb20e1b6-e30b-11e5-8acc-ee407b18b3ed.png)

![s3](https://cloud.githubusercontent.com/assets/14961790/13547601/d5f5c61a-e30b-11e5-8923-4eb9c2801ca9.png)

**Comment by thangtyt** [comment]
i found this error and fixed it. 
Please pull new code and send feedback for me.
Thanks
