### ISSUE TITLE
Cannot login into admin

### ISSUE THREAD

**Issue by nguyentrongbang** [arrowjs/CMS#30]
I'm choosing `postgres` as main database. On statup, it creates an admin account:

1;"xw/lZzLWWyMdUxxZOr4ef/kYfzrltc77oMDJvy0ULnDw+Z8l1DIxXRavk8xI0NrMMNq4303Y7SbbtlJkS/GLFg==";"admin@example.com";"2016-03-08 00:30:48.165335+07";"";"publish";"Administrator";"/img/noImage.png";"nPxKukG8p7seoPRfm9v1zZ0miGRL0eytJEXqm900AhksMpwCQp";1;"1";;"";;""

But I cannot login with this account (**admin@example.com / 123456**)

Here is error after login

> GET /admin/login 200 64.893 ms - 3182
> Error: Can't set headers after they are sent.
>     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
>     at ServerResponse.header (C:\xampp\htdocs\CMS\node_modules\express\lib\response.js:718:10)
>     at ServerResponse.send (C:\xampp\htdocs\CMS\node_modules\express\lib\response.js:163:12)
>     at ServerResponse.json (C:\xampp\htdocs\CMS\node_modules\express\lib\response.js:249:15)
>     at ServerResponse.send (C:\xampp\htdocs\CMS\node_modules\express\lib\response.js:151:21)
>     at C:\xampp\htdocs\CMS\node_modules\arrowjs\libs\ArrowApplication.js:920:17
>     at Layer.handle_error (C:\xampp\htdocs\CMS\node_modules\express\lib\router\layer.js:71:5)
>     at trim_prefix (C:\xampp\htdocs\CMS\node_modules\express\lib\router\index.js:310:13)
>     at C:\xampp\htdocs\CMS\node_modules\express\lib\router\index.js:280:7
>     at Function.process_params (C:\xampp\htdocs\CMS\node_modules\express\lib\router\index.js:330:12)
>     at next (C:\xampp\htdocs\CMS\node_modules\express\lib\router\index.js:271:10)
>     at Layer.handle_error (C:\xampp\htdocs\CMS\node_modules\express\lib\router\layer.js:67:12)
>     at trim_prefix (C:\xampp\htdocs\CMS\node_modules\express\lib\router\index.js:310:13)
>     at C:\xampp\htdocs\CMS\node_modules\express\lib\router\index.js:280:7
>     at Function.process_params (C:\xampp\htdocs\CMS\node_modules\express\lib\router\index.js:330:12)
>     at next (C:\xampp\htdocs\CMS\node_modules\express\lib\router\index.js:271:10)
>     at Layer.handle_error (C:\xampp\htdocs\CMS\node_modules\express\lib\router\layer.js:67:12)
>     at trim_prefix (C:\xampp\htdocs\CMS\node_modules\express\lib\router\index.js:310:13)
>     at C:\xampp\htdocs\CMS\node_modules\express\lib\router\index.js:280:7
>     at Function.process_params (C:\xampp\htdocs\CMS\node_modules\express\lib\router\index.js:330:12)
>     at next (C:\xampp\htdocs\CMS\node_modules\express\lib\router\index.js:271:10)
>     at Layer.handle_error (C:\xampp\htdocs\CMS\node_modules\express\lib\router\layer.js:67:12)

Environtment:
- OS: Windows
- postgresql: 9.5 (lastest version for Windows)
- node v4.3.2

**Comment by lephuhai** [comment]
I don't get it, can you make me more details about problem or you can checkout latest source code version from master branch. If you have any issues then report to me. Maybe, this bug has existed previous version.
