### ISSUE TITLE
Could not get config data from a customized config file

### ISSUE THREAD

**Issue by lethanhtrung2020** [arrowjs/CMS#31]
Hi,
I created my own a config file as mydb.js in config folder. The code is as below 

module.exports = {
    mydbpath: "...",
    mydbpassword: "..."
};

However, it return empty when I try to get these config in my controllers as code below
let dbpath = app.getConfig("mydbpath");

Please check the issue.
Thanks

**Comment by trquoccuong** [comment]
This is arrow convention, for make a new config, you can put in on env/default.js or env/<environment name >.js

**Comment by lethanhtrung2020** [comment]
Hi,
I tested in both cases:
1. Create new file in env folder
2. Add config to default.js

Both doesn't work.

This is the code of changing default.js

--------- default.js-------------
'use strict';

module.exports = {
    my_config:"test"

## };

-------- code in a feature -------
var redis_conf = app.getConfig("redis_prefix");
console.log(redis_conf);
var my_config = app.getConfig("my_config");

## console.log(my_config);

The first log out is correct: ArrowCMS_
The second log is undefined 

Please test and guide to fix the issue.
Thanks
