### ISSUE TITLE
Request for CDN support 

### ISSUE THREAD

**Issue by lethanhtrung2020** [arrowjs/CMS#32]
Hi,
This is not an issue but a desire. Can ArrowJS have a solution for uploading and access via other domain. It would be helpful to utilize CDN for better performance.
e.g: 
- main site : www,mysite.com
- uploaded resource & static assets: static.mysite.com

AWS S3  + Cloudfront support should be great.
Thanks
Trung

**Comment by trquoccuong** [comment]
Nodejs is not good at serving static resource. Best solution is config CDN or S3 in nginx . Contact me if you need the nginx config
