### ISSUE TITLE
Question about Config

### ISSUE THREAD

**Issue by lethanhtrung2020** [arrowjs/CMS#34]
Hi,
I have some questions:
1. There are 2 configurations related to DB
- in config/env/development.js
- in config/database.js

so what is the different?
1. my understanding is the development.js is config for dev environement. How to have config for production and turn system to production mode
2. How to change the script to init db in case it doesn't exist. The local.js in strategies folder contains code for admin account initialization only.

Thanks
Trung

**Comment by trquoccuong** [comment]
the env folder use to setup config base on NODE_ENV. This config will override the config/
