### ISSUE TITLE
Widgets Manager - Could not save

### ISSUE THREAD

**Issue by lethanhtrung2020** [arrowjs/CMS#37]
Hi,
I download the last version of ArrowJS CMS and run install. Everything is ok.
However, the widget manager could not perform saving function. Just drag and drop a widget (e.g: recent posts to the Right side bar and click save. No error message found, server console shows 200 response. But if you open Chrome console then there is an error as image below

![image](https://cloud.githubusercontent.com/assets/14961790/20615402/2b7b949a-b30c-11e6-9be6-dfff486402e0.png)

Please help.
Thanks
Trung

**Comment by trquoccuong** [comment]
I cant remake this problem , let try new version 0.0.2

**Comment by lephuhai** [comment]
Yes, this is definitely a bug.  I fixed some bugs in 1e1fc9e
