### ISSUE TITLE
Warning on Ubuntu server

### ISSUE THREAD

**Issue by lethanhtrung2020** [arrowjs/CMS#39]
Hi,
There is a warning as I run ArrowJS CMS. Below is the screen capture for your reference.
![image](https://cloud.githubusercontent.com/assets/14961790/21228646/2d59a594-c311-11e6-8f9d-aa62fb109615.png)
Please check if any potential issue may have. 
Thanks
Trung

**Comment by lephuhai** [comment]
Don't worry about it, everything ok. Thanks for your report.
