### ISSUE TITLE
Can't run ArrowCMS after a fresh clone

### ISSUE THREAD

**Issue by anhntbk08** [arrowjs/CMS#8]
Hi Team,

After cloning this repository, i can't make this run.

Seem that you forgot adding lodash to package.json, i added then i met this issue.
![image](https://cloud.githubusercontent.com/assets/2239780/11360495/94e8bd98-92b7-11e5-9857-40db54229e49.png)

Any idea to fix this?

Btw [your website](http://arrowjs.io/) is pointing to old repository :(

**Comment by TechMaster** [comment]
Hi Anh,

We word hard to release Arrowjs Core and develop several examples in Example repo first. CMS repo is the new CMS of ArrowCMS. It is unstable until end of Dec 7th 2016.

I will comeback to this read when CMS is stable.
